---
- hosts: webservers
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install Django
      pip: name=django state=present
    - name: Install Boto
      pip: name=boto state=present
    - name: Synchronize Root Directory
      synchronize: src=/etc/ansible/calculator/ dest=~/calculator
...
